## -----------------------
##  assets directory
## -----------------------

[[mounts]]
    source = 'assets'
    target = 'assets/reblock'


## -----------------------
##  based directory
## -----------------------

[[mounts]]
    source = 'based'
    target = 'layouts/[sectioname]'


## -----------------------
##  engine directory
## -----------------------

[[mounts]]
    source = 'engine/blocks'
    target = 'layouts/partials/shortcodes'

[[mounts]]
    source = 'engine/paged'
    target = 'layouts/_default'

[[mounts]]
    source = 'engine/parted'
    target = 'layouts/partials/reblock/parted/'

[[mounts]]
    source = 'engine/section'
    target = 'layouts/partials/reblock/section/'


## -----------------------
##  library directory
## -----------------------

[[mounts]]
    source = 'library/format'
    target = 'archetypes'

[[mounts]]
    source = 'library/global'
    target = 'layouts/partials'

[[mounts]]
    source = 'library/interns'
    target = 'layouts/partials/reblock/interns'

[[mounts]]
    source = 'library/langua'
    target = 'i18n'

[[mounts]]
    source = 'library/metad'
    target = 'layouts/partials/metadata'



## -----------------------
##  module directory
## -----------------------

[[mounts]]
    source = 'module'
    target = 'static'


## -----------------------
##  datum directory
## -----------------------

[[mounts]]
    source = 'source/datum'
    target = 'data'

[[mounts]]
    source = 'source/media/anima'
    target = 'assets/anima'

[[mounts]]
    source = 'source/media/audio'
    target = 'assets/audio'

[[mounts]]
    source = 'source/media/image'
    target = 'assets/video'

[[mounts]]
    source = 'source/media/video'
    target = 'assets/video'