## -----------------------
##  assets directory
## -----------------------

[[mounts]]
    source = 'assets'
    target = 'assets/reblock'


## -----------------------
##  based directory
## -----------------------

[[mounts]]
    source = 'based'
    target = 'layouts/[sectioname]'


## -----------------------
##  library directory
## -----------------------


[[mounts]]
    source = 'library/globals'
    target = 'layouts/partials'

[[mounts]]
    source = 'library/interns'
    target = 'layouts/partials/reblock/interns'

[[mounts]]
    source = 'library/langua'
    target = 'i18n'

## -----------------------
##  render directory
## -----------------------


[[mounts]]
    source = 'render/blocks'
    target = 'layouts/partials/shortcodes'


[[mounts]]
    source = 'render/parted'
    target = 'layouts/partials/blocks'


## -----------------------
##  skined directory
## -----------------------

[[mounts]]
    source = 'skined'
    target = 'layouts/partials/blocks/skined'


## -----------------------
##  datum directory
## -----------------------

[[mounts]]
    source = 'source/datum'
    target = 'data'

[[mounts]]
    source = 'source/media/anima'
    target = 'assets/anima'

[[mounts]]
    source = 'source/media/audio'
    target = 'assets/audio'

[[mounts]]
    source = 'source/media/image'
    target = 'assets/video'

[[mounts]]
    source = 'source/media/video'
    target = 'assets/video'